// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID           int32        `json:"id"`
	CreatedAt    sql.NullTime `json:"createdAt"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"-"`
}

type Chat struct {
	ID        int32                 `json:"id"`
	CreatedAt sql.NullTime          `json:"createdAt"`
	Messages  pqtype.NullRawMessage `json:"messages"`
	AccountID int32                 `json:"accountId"`
}

type Document struct {
	ID        int32          `json:"id"`
	CreatedAt sql.NullTime   `json:"createdAt"`
	Name      string         `json:"name"`
	Text      sql.NullString `json:"text"`
	FilePath  sql.NullString `json:"filePath"`
	Embedding interface{}    `json:"embedding"`
	AccountID int32          `json:"accountId"`
}
